//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/DEVInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DEVInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DEVInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DEVInputs"",
    ""maps"": [
        {
            ""name"": ""DevInputs"",
            ""id"": ""5f15aa24-1a3c-4242-9b0b-0a2b4bdef946"",
            ""actions"": [
                {
                    ""name"": ""RemoveRecycleItem"",
                    ""type"": ""Button"",
                    ""id"": ""75015452-6209-47de-bd92-c631aa19587f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmRecycle"",
                    ""type"": ""Button"",
                    ""id"": ""1460ce5c-fcd7-4b3c-b017-6eaf3b44ead2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""df83202a-eed8-4344-80ff-298de1b02ff7"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveRecycleItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83d63089-0d57-493b-8c54-803a6f096b74"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmRecycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DevInputs
        m_DevInputs = asset.FindActionMap("DevInputs", throwIfNotFound: true);
        m_DevInputs_RemoveRecycleItem = m_DevInputs.FindAction("RemoveRecycleItem", throwIfNotFound: true);
        m_DevInputs_ConfirmRecycle = m_DevInputs.FindAction("ConfirmRecycle", throwIfNotFound: true);
    }

    ~@DEVInputs()
    {
        UnityEngine.Debug.Assert(!m_DevInputs.enabled, "This will cause a leak and performance issues, DEVInputs.DevInputs.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DevInputs
    private readonly InputActionMap m_DevInputs;
    private List<IDevInputsActions> m_DevInputsActionsCallbackInterfaces = new List<IDevInputsActions>();
    private readonly InputAction m_DevInputs_RemoveRecycleItem;
    private readonly InputAction m_DevInputs_ConfirmRecycle;
    public struct DevInputsActions
    {
        private @DEVInputs m_Wrapper;
        public DevInputsActions(@DEVInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @RemoveRecycleItem => m_Wrapper.m_DevInputs_RemoveRecycleItem;
        public InputAction @ConfirmRecycle => m_Wrapper.m_DevInputs_ConfirmRecycle;
        public InputActionMap Get() { return m_Wrapper.m_DevInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DevInputsActions set) { return set.Get(); }
        public void AddCallbacks(IDevInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_DevInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DevInputsActionsCallbackInterfaces.Add(instance);
            @RemoveRecycleItem.started += instance.OnRemoveRecycleItem;
            @RemoveRecycleItem.performed += instance.OnRemoveRecycleItem;
            @RemoveRecycleItem.canceled += instance.OnRemoveRecycleItem;
            @ConfirmRecycle.started += instance.OnConfirmRecycle;
            @ConfirmRecycle.performed += instance.OnConfirmRecycle;
            @ConfirmRecycle.canceled += instance.OnConfirmRecycle;
        }

        private void UnregisterCallbacks(IDevInputsActions instance)
        {
            @RemoveRecycleItem.started -= instance.OnRemoveRecycleItem;
            @RemoveRecycleItem.performed -= instance.OnRemoveRecycleItem;
            @RemoveRecycleItem.canceled -= instance.OnRemoveRecycleItem;
            @ConfirmRecycle.started -= instance.OnConfirmRecycle;
            @ConfirmRecycle.performed -= instance.OnConfirmRecycle;
            @ConfirmRecycle.canceled -= instance.OnConfirmRecycle;
        }

        public void RemoveCallbacks(IDevInputsActions instance)
        {
            if (m_Wrapper.m_DevInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDevInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_DevInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DevInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DevInputsActions @DevInputs => new DevInputsActions(this);
    public interface IDevInputsActions
    {
        void OnRemoveRecycleItem(InputAction.CallbackContext context);
        void OnConfirmRecycle(InputAction.CallbackContext context);
    }
}
