//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/MenuInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuInputs"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""a82944a8-13a9-4b7d-8c20-11f540756bc5"",
            ""actions"": [
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""0ddda743-3460-498c-a3b2-5d811fed267d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleX"",
                    ""type"": ""Button"",
                    ""id"": ""0f06df01-5d9b-4fb6-9596-0e09ca72b81d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""7736d3f3-621a-4f47-83cb-7b0a009666f4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recipe"",
                    ""type"": ""Button"",
                    ""id"": ""92e9e510-1cd2-44eb-875f-1afddf61b87b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Friends"",
                    ""type"": ""Button"",
                    ""id"": ""e1f9420e-4ca7-4d6b-8343-9522b413d4c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quests"",
                    ""type"": ""Button"",
                    ""id"": ""3dd94d64-6474-4a11-ba48-322fc59c30fa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Calender"",
                    ""type"": ""Button"",
                    ""id"": ""18c8a8e6-2ecb-40b1-b880-4ad834acb28d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""e0632335-1edf-484e-807f-ca8b1bf8b081"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c18173e9-1b61-4b83-ae63-aa745fb7ac90"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0184250-41da-4f37-8330-a6b667fef845"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a148b750-22d6-4ea8-9ec6-3accf5a4af95"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcf86201-6e0a-4320-a0e5-9d11f75c2bc0"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f492fe43-cfe5-4b95-8b9a-2b0797a28ada"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Friends"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""790c77e3-d6f2-4608-abb4-f935018f10d6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quests"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c76f8c9e-d980-4ceb-b057-c8138cf25eca"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Calender"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01fc3053-6208-4ada-8a67-5c382377d619"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c216495-e911-475a-a45f-cec28e405f1d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Inventory = m_UI.FindAction("Inventory", throwIfNotFound: true);
        m_UI_ToggleX = m_UI.FindAction("ToggleX", throwIfNotFound: true);
        m_UI_Map = m_UI.FindAction("Map", throwIfNotFound: true);
        m_UI_Recipe = m_UI.FindAction("Recipe", throwIfNotFound: true);
        m_UI_Friends = m_UI.FindAction("Friends", throwIfNotFound: true);
        m_UI_Quests = m_UI.FindAction("Quests", throwIfNotFound: true);
        m_UI_Calender = m_UI.FindAction("Calender", throwIfNotFound: true);
        m_UI_CloseMenu = m_UI.FindAction("CloseMenu", throwIfNotFound: true);
    }

    ~@MenuInputs()
    {
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, MenuInputs.UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Inventory;
    private readonly InputAction m_UI_ToggleX;
    private readonly InputAction m_UI_Map;
    private readonly InputAction m_UI_Recipe;
    private readonly InputAction m_UI_Friends;
    private readonly InputAction m_UI_Quests;
    private readonly InputAction m_UI_Calender;
    private readonly InputAction m_UI_CloseMenu;
    public struct UIActions
    {
        private @MenuInputs m_Wrapper;
        public UIActions(@MenuInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Inventory => m_Wrapper.m_UI_Inventory;
        public InputAction @ToggleX => m_Wrapper.m_UI_ToggleX;
        public InputAction @Map => m_Wrapper.m_UI_Map;
        public InputAction @Recipe => m_Wrapper.m_UI_Recipe;
        public InputAction @Friends => m_Wrapper.m_UI_Friends;
        public InputAction @Quests => m_Wrapper.m_UI_Quests;
        public InputAction @Calender => m_Wrapper.m_UI_Calender;
        public InputAction @CloseMenu => m_Wrapper.m_UI_CloseMenu;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @ToggleX.started += instance.OnToggleX;
            @ToggleX.performed += instance.OnToggleX;
            @ToggleX.canceled += instance.OnToggleX;
            @Map.started += instance.OnMap;
            @Map.performed += instance.OnMap;
            @Map.canceled += instance.OnMap;
            @Recipe.started += instance.OnRecipe;
            @Recipe.performed += instance.OnRecipe;
            @Recipe.canceled += instance.OnRecipe;
            @Friends.started += instance.OnFriends;
            @Friends.performed += instance.OnFriends;
            @Friends.canceled += instance.OnFriends;
            @Quests.started += instance.OnQuests;
            @Quests.performed += instance.OnQuests;
            @Quests.canceled += instance.OnQuests;
            @Calender.started += instance.OnCalender;
            @Calender.performed += instance.OnCalender;
            @Calender.canceled += instance.OnCalender;
            @CloseMenu.started += instance.OnCloseMenu;
            @CloseMenu.performed += instance.OnCloseMenu;
            @CloseMenu.canceled += instance.OnCloseMenu;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @ToggleX.started -= instance.OnToggleX;
            @ToggleX.performed -= instance.OnToggleX;
            @ToggleX.canceled -= instance.OnToggleX;
            @Map.started -= instance.OnMap;
            @Map.performed -= instance.OnMap;
            @Map.canceled -= instance.OnMap;
            @Recipe.started -= instance.OnRecipe;
            @Recipe.performed -= instance.OnRecipe;
            @Recipe.canceled -= instance.OnRecipe;
            @Friends.started -= instance.OnFriends;
            @Friends.performed -= instance.OnFriends;
            @Friends.canceled -= instance.OnFriends;
            @Quests.started -= instance.OnQuests;
            @Quests.performed -= instance.OnQuests;
            @Quests.canceled -= instance.OnQuests;
            @Calender.started -= instance.OnCalender;
            @Calender.performed -= instance.OnCalender;
            @Calender.canceled -= instance.OnCalender;
            @CloseMenu.started -= instance.OnCloseMenu;
            @CloseMenu.performed -= instance.OnCloseMenu;
            @CloseMenu.canceled -= instance.OnCloseMenu;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IUIActions
    {
        void OnInventory(InputAction.CallbackContext context);
        void OnToggleX(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnRecipe(InputAction.CallbackContext context);
        void OnFriends(InputAction.CallbackContext context);
        void OnQuests(InputAction.CallbackContext context);
        void OnCalender(InputAction.CallbackContext context);
        void OnCloseMenu(InputAction.CallbackContext context);
    }
}
