jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 6000.0.32f1

      # Rename and move build
      - name: Prepare custom build folder
        run: |
          mkdir CustomBuild
          mv build/StandaloneWindows64/* CustomBuild/
          mv CustomBuild/StandaloneWindows64.exe CustomBuild/TideUp.exe

      # Zip it
      - name: Zip build
        run: zip -r Build.zip CustomBuild

      # Upload it
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: Build.zip
